services:

  lb-mongodb:
    image: mongo:8.0.6
    ports:
      - "27017:27017" # expose port on internal and external networks
    networks:
      - lb-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin # Set the root username for MongoDB
      MONGO_INITDB_ROOT_PASSWORD: admin # Set a strong root password for MongoDB

  lb-benchmark-ingestion-server-1:
    build:
      context: ../../..
      dockerfile: ./docker/applications/JavaApp/Dockerfile
    expose:
      - "60051" # expose to internal docker network on 60051
    networks:
      - lb-network
    command:
      - "-Ddp.MongoClient.dbHost=lb-mongodb"
      - "-cp"
      - "/app/dp-service.jar"
      - "com.ospreydcs.dp.service.ingest.benchmark.BenchmarkIngestionGrpcServer"

  lb-benchmark-ingestion-server-2:
    build:
      context: ../../..
      dockerfile: ./docker/applications/JavaApp/Dockerfile
    expose:
      - "60051" # expose to internal docker network on 60051
    networks:
      - lb-network
    command:
      - "-Ddp.MongoClient.dbHost=lb-mongodb"
      - "-cp"
      - "/app/dp-service.jar"
      - "com.ospreydcs.dp.service.ingest.benchmark.BenchmarkIngestionGrpcServer"

  lb-envoy:
    image: envoyproxy/envoy:v1.18-latest
    volumes:
      - ./config/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080"
    networks:
      - lb-network

networks:
  lb-network:
    driver: bridge
