services:

  benchmark-ingestion-server-1:
    container_name: dp-benchmark-ingestion-server-1
    build:
      context: ../../..
      dockerfile: ./docker/services/BenchmarkIngestionGrpcServer/Dockerfile
    expose:
      - "60051" # expose to internal docker network on 60051
    networks:
      - grpc-network

  benchmark-ingestion-server-2:
    container_name: dp-benchmark-ingestion-server-2
    build:
      context: ../../..
      dockerfile: ./docker/services/BenchmarkIngestionGrpcServer/Dockerfile
    expose:
      - "60051" # expose to internal docker network on 60051
    networks:
      - grpc-network

  envoy:
    image: envoyproxy/envoy:v1.18-latest
    container_name: dp-envoy-load-balancer
    volumes:
      - ./config/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080"
    networks:
      - grpc-network

networks:
  grpc-network:
    driver: bridge
