# Deployment Instructions for Ingestion Load Balancer
# 
# This file contains commands to deploy the Kubernetes configuration
# Run these commands in order:

# 1. For minikube: Load Docker images into minikube
minikube image load dp-ingestion-service:latest

# 2. Apply all configurations
kubectl apply -f 00-namespace.yaml
kubectl apply -f 01-mongodb-deployment.yaml
kubectl apply -f 02-mongodb-service.yaml
kubectl apply -f 03-ingestion-deployment.yaml
kubectl apply -f 04-ingestion-service.yaml
kubectl apply -f 05-hpa.yaml

# 3. Check deployment status
kubectl get all -n ingestion-lb

# 4. Get service endpoints for external access
kubectl get svc -n ingestion-lb
# MongoDB: minikube_ip:30017
# Ingestion gRPC: minikube_ip:31406  
# Ingestion HTTP: minikube_ip:32607

# 5. Watch HPA scaling in action
kubectl get hpa -n ingestion-lb -w

# 6. Generate load to test autoscaling
# Run your benchmark client against 192.168.49.2:31406 (or get minikube IP with: minikube ip)
# You should see HPA automatically scale up the ingestion pods

# 7. Monitor logs
kubectl logs -n ingestion-lb deployment/ingestion-service -f

# 8. Scale manually for testing
kubectl scale deployment ingestion-service --replicas=5 -n ingestion-lb

# 9. Cleanup when done
kubectl delete namespace ingestion-lb