apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
  namespace: dp-ecosystem
  labels:
    app: ingestion-service
    component: backend
spec:
  type: NodePort  # Use NodePort for snap k8s - LoadBalancer stays pending
  selector:
    app: ingestion-service
  ports:
  - port: 8080        # External port (like Envoy was using)
    targetPort: 50051  # Internal container port (production service)
    nodePort: 32607    # Fixed external port for HTTP/gRPC-Web
    protocol: TCP
    name: grpc-web
  # For gRPC, you might also want to expose the raw gRPC port
  - port: 50051
    targetPort: 50051
    nodePort: 31406    # Fixed external port for gRPC
    protocol: TCP
    name: grpc