apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: dp-ecosystem
  labels:
    app: mongodb
    component: database
spec:
  replicas: 1  # MongoDB typically runs as single instance
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:8.0.6
        ports:
        - containerPort: 27017
          name: mongo
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "admin"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        # For production, you'd add persistent volume claims here
        # volumeMounts:
        # - name: mongodb-storage
        #   mountPath: /data/db
      # volumes:
      # - name: mongodb-storage
      #   persistentVolumeClaim:
      #     claimName: mongodb-pvc