apiVersion: v1
kind: Service
metadata:
  name: query-service
  namespace: dp-ecosystem
  labels:
    app: query-service
    component: backend
spec:
  type: NodePort  # Use NodePort for snap k8s - LoadBalancer stays pending
  selector:
    app: query-service
  ports:
  - port: 8081        # External port (different from ingestion)
    targetPort: 50052  # Internal container port (query service)
    nodePort: 32608    # Fixed external port for HTTP/gRPC-Web
    protocol: TCP
    name: grpc-web
  # For gRPC, you might also want to expose the raw gRPC port
  - port: 50052
    targetPort: 50052
    nodePort: 31407    # Fixed external port for gRPC
    protocol: TCP
    name: grpc